### ISSUE TITLE
The application is not built on Android Studio

### ISSUE THREAD

**Issue by low-bin** [chec/chopchop-ionic#1]
I was unable to build the application in Android Studio. The following error is displayed:

Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: root project 'android', project ':capacitor-android', project ':capacitor-cordova-android-plugins'
Affected Modules: app

Can you help me please?

**Comment by robbieaverill** [comment]
Hi @low-bin, the link you've shared mentions that while deprecated, "JCenter will allow downloads of existing artifacts indefinitely."

Are these warnings you're receiving, or errors preventing your builds from completing?

**Comment by craigtweedy** [comment]
Hey @low-bin, checked my side and the warning comes through too, but doesn't prevent me from building the project. Are there any other errors in the build logs? 

Attempted to build without `jcenter()` too but looks like there's some linked dependencies through Google dependencies that can't be found. I'm checking if there's a simple replacement, but as @robbieaverill mentioned existing artifacts should be available indefinitely.

**Comment by robbieaverill** [comment]
Feel free to reopen if you'd like to discuss this further.
